// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClientItem: typeof import('./components/client/ClientItem.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    Loading: typeof import('./components/Loading.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    MessageItem: typeof import('./components/message/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('@headlessui/vue')['Switch']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    TabPanel: typeof import('@headlessui/vue')['TabPanel']
    TabPanels: typeof import('@headlessui/vue')['TabPanels']
    TheClientSidebar: typeof import('./components/client/TheClientSidebar.vue')['default']
    TheHeader: typeof import('./components/header/TheHeader.vue')['default']
    TheHeaderChangeRoom: typeof import('./components/header/TheHeaderChangeRoom.vue')['default']
    TheHeaderDropdown: typeof import('./components/header/TheHeaderDropdown.vue')['default']
    TheMessageBody: typeof import('./components/message/TheMessageBody.vue')['default']
    TheMessageCompose: typeof import('./components/message/TheMessageCompose.vue')['default']
    TheMessageHeader: typeof import('./components/message/TheMessageHeader.vue')['default']
    TheModalSettings: typeof import('./components/settings/TheModalSettings.vue')['default']
    TheNotify: typeof import('./components/notify/TheNotify.vue')['default']
    TheSettingsAnsweringMachine: typeof import('./components/settings/TheSettingsAnsweringMachine.vue')['default']
    TheSettingsAnsweringMachineForm: typeof import('./components/settings/TheSettingsAnsweringMachineForm.vue')['default']
    TheSettingsSoundNotify: typeof import('./components/settings/TheSettingsSoundNotify.vue')['default']
    TheSettingsTabs: typeof import('./components/settings/TheSettingsTabs.vue')['default']
    TheSidebarChangeLang: typeof import('./components/sidebar/TheSidebarChangeLang.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}

export {}
